# Dockerfile for a primary node
FROM jfrog-docker-reg2.bintray.io/jfrog/artifactory-pro:5.4.1

MAINTAINER shikharr@jfrog.com


### Atomic/OpenShift Labels - https://github.com/projectatomic/ContainerApplicationGenericLabels
LABEL name="Artifactory Pro" \
      vendor="JFrog" \
      version="5.4.1" \
      release="1" \
      summary="JFrog Artifcatory Pro is a...." \
      description="Artifcatory Pro will do ....." \
### Required labels above - recommended below
      url="https://www.jfrog.com" \
      run='docker run -tdi --name ${NAME} ${IMAGE}' \
      io.k8s.description="Artifactory Pro will do ....." \
      io.k8s.display-name="Artifactory Pro" \
      io.openshift.expose-services="" \
      io.openshift.tags="jfrog,artificatory pro"

### Atomic Help File - help.1 already in Markdown and provided with Doockerfile by RH as a simple test
### https://github.com/projectatomic/container-best-practices/blob/master/creating/help.adoc
COPY help.1 /help.1

### add licenses to this directory
### put all end user license agreements in this directory
COPY licenses /licenses

# We download all the usual JDBC drivers available so we can
# configure them at runtime
RUN curl -L -o /opt/jfrog/artifactory/tomcat/lib/postgresql-42.0.0.jre6.jar https://jdbc.postgresql.org/download/postgresql-42.0.0.jre6.jar

ADD artifactory.config.xml /tmp/artifactory.config.xml

# Copy the run script
COPY run.sh /runArtifactory.sh
COPY entrypoint-artifactory.sh /
RUN chmod +x /entrypoint-artifactory.sh

#dynamic configuration
COPY server.xml /opt/jfrog/artifactory/tomcat/conf/server.xml
COPY nginx.ftl /tmp/nginx.ftl
COPY internalUser.groovy /tmp/internalUser.groovy
COPY binarystore.xml /tmp/binarystore.xml

# Pre-Populated keys
ADD HA/keys/private.key /var/opt/jfrog/artifactory/access/etc/keys/private.key
ADD HA/keys/root.crt /var/opt/jfrog/artifactory/access/etc/keys/root.crt
ADD HA/communication.key $ARTIFACTORY_DATA/communication.key

EXPOSE 8081 10042 5001

ENTRYPOINT /runArtifactory.sh
